/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pt.rosamindo.jaya.mandiri;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

public class HasilPerhitungan extends javax.swing.JInternalFrame {
    DefaultTableModel tabelNormalisasi;
    DefaultTableModel tabelPeringkat;
    koneksi conn= new koneksi();
    public HasilPerhitungan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_Normalisasi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabel_Hasil_Perhitungan = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Hasil Perhitungan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 210, 30));

        Tabel_Normalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Normalisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_NormalisasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel_Normalisasi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 1250, 160));

        jButton1.setText("Normalisasi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        Tabel_Hasil_Perhitungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Hasil_Perhitungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_Hasil_PerhitunganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabel_Hasil_Perhitungan);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 1250, 160));

        jButton2.setText("Hasil Perhtungan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, -1));

        jButton3.setText("Penetuan lolos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, 140, -1));

        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tabelModelNormalisasi(){
       tabelNormalisasi = new DefaultTableModel();
       tabelNormalisasi.addColumn("ID");
       tabelNormalisasi.addColumn("Nama Karyawan");
       tabelNormalisasi.addColumn("Wawancara (C1)");
       tabelNormalisasi.addColumn("Test Kepribadian (C2)");
       tabelNormalisasi.addColumn("IPK (C3)");
       tabelNormalisasi.addColumn("Test Bidang (C4)");
       tabelNormalisasi.addColumn("Pengalaman Bekerja (C5)");
       Tabel_Normalisasi.setModel(tabelNormalisasi);
    }
    
    
    public  void normalisasi(){
        LinkedList max = new LinkedList();
        
        
        try{
            ResultSet res = conn.ambilData("select max(C1_Wawancara),"+ 
                "max(C2_Test_Kepribadian), "+
                "max(C3_IPK), "+
                "max(C4_Test_Bidang),"+
                "max(C5_Pengalaman_Bekerja)"+
                "from "+
                "data_karyawan ");
            
            while (res.next()){
                max.add(res.getString(1));
                max.add(res.getString(2));
                max.add(res.getString(3));
                max.add(res.getString(4));
                max.add(res.getString(5));
            }
            ResultSet res2 = conn.ambilData("select *"+"from "+"data_karyawan ");
            tabelModelNormalisasi();
            
            while (res2.next()){
                tabelNormalisasi.addRow(new Object[]{res2.getString(1),res2.getString(2),
                    (res2.getFloat(3)/Float.valueOf(max.get(0).toString())),
                    (res2.getFloat(4)/Float.valueOf(max.get(1).toString())),
                    (res2.getFloat(5)/Float.valueOf(max.get(2).toString())),
                    (res2.getFloat(6)/Float.valueOf(max.get(3).toString())),
                    (res2.getFloat(7)/Float.valueOf(max.get(4).toString())),
                    (Float.valueOf(max.get(4).toString())/res2.getFloat(7))});
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public void tabelmodelPeringkat(){
        try {
            tabelPeringkat = new DefaultTableModel();
            tabelPeringkat.addColumn("ID");
            tabelPeringkat.addColumn("Nama");
            tabelPeringkat.addColumn("Hasil Perhitungan");
            
            Tabel_Hasil_Perhitungan.setModel(tabelPeringkat);
            ResultSet res = conn.ambilData("SELECT * FROM data_hasil_perhitungan");
             while (res.next()){
                         tabelPeringkat.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)}); 
                     }
        } catch (SQLException ex) {
            Logger.getLogger(HasilPerhitungan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cariperingkat(){
        try{
            LinkedList mm = new LinkedList();
            ResultSet res3 = conn.ambilData("SELECT * FROM data_bobot");
            tabelmodelPeringkat();
            while (res3.next()){
                 mm.add(res3.getString(1));
                 mm.add(res3.getString(2));
                 mm.add(res3.getString(3));
                 mm.add(res3.getString(4));
                 mm.add(res3.getString(5));
            }
           for (int t = 0; t < Tabel_Normalisasi.getRowCount(); t++) {
                String sql = "DELETE FROM data_hasil_perhitungan WHERE ID= ID";
                conn.simpanData(sql);
            }
            for (int x = 0; x < Tabel_Normalisasi.getRowCount(); x++){
                double r1;
                double r2;
                double r3;
                double r4;
                double r5;
                double r6;
                double r7;
                double w;
                
                r1 = (Float.valueOf(Tabel_Normalisasi.getValueAt(x, 2).toString())*Float.valueOf(mm.get(0).toString()));
                r2=(Float.valueOf(Tabel_Normalisasi.getValueAt(x, 3).toString())*Float.valueOf(mm.get(1).toString()));
                r3=(Float.valueOf(Tabel_Normalisasi.getValueAt(x, 4).toString())*Float.valueOf(mm.get(2).toString()));
                r4=(Float.valueOf(Tabel_Normalisasi.getValueAt(x, 5).toString())*Float.valueOf(mm.get(3).toString()));
                r5=(Float.valueOf(Tabel_Normalisasi.getValueAt(x, 6).toString())*Float.valueOf(mm.get(4).toString()));
                
                w=r1+r2+r3+r4+r5;
                
                String sql = "insert into data_hasil_perhitungan values"+"(  '"+Tabel_Normalisasi.getValueAt(x, 0).toString()+"' ,'"+Tabel_Normalisasi.getValueAt(x, 1).toString()+"' , "+" '"+w+"' )";
                conn.simpanData(sql);
            }
            tabelModelNormalisasi();
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    private void Tabel_NormalisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_NormalisasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabel_NormalisasiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        normalisasi();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Tabel_Hasil_PerhitunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_Hasil_PerhitunganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabel_Hasil_PerhitunganMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cariperingkat();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HasilLolosDanTidakLolos BarangKeluar = new HasilLolosDanTidakLolos();
        BarangKeluar.setVisible(true);
        this.getDesktopPane().add(BarangKeluar);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_Hasil_Perhitungan;
    private javax.swing.JTable Tabel_Normalisasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void EXIT_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
